---
title: "Household Structure (Preliminary)"
author: "Diego Campos"
date: "10/8/2020"
output: powerpoint_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = F, 
                      message = F, 
                      fig.height = 4, 
                      fig.width = 8)
```

```{r load-libraries-functions}

source(
  here::here(
    'R', 
    'presentation_setup.R'
  )
)


```

```{r load-data}

analysis_data <- 
  load_data$load_population_estimates()[['q2_household']]




```

```{r}
analysis_data <- 
  modify(.x = analysis_data, 
         .f = ~.x %>% mutate(oy_flag = figure_helpers$format_oy_variable(oy_flag)))

erase_y_axis = 
   theme(
    axis.text.y = element_blank(), 
    axis.line.y = element_blank(), 
    axis.title.y = element_blank(), 
    axis.ticks.y = element_blank()
  )

erase_x_legend = 
  theme(
    axis.title.x = element_blank()
  )


# Settings for the lower error bar
# other option is percent_low
error_bar_low <- 
  rlang::sym('percent')

# color contrasts between Connected Youth and Opportunity Youth
# color_contrast <- 
#   c(`Connected Youth` = "#800000", `Opportunity Youth` = '#D5802B')

color_contrast <- 
  c(`Connected Youth` = "#767676", `Opportunity Youth` = '#D5802B')
```

```{r}
basic_plot <- function(data, fill_label = NULL){
  
  fill_col = names(data)[2] %>% rlang::sym()
  
  data %>% 
    ggplot(aes(x = oy_flag, y = percent, fill = !!fill_col)) + 
    geom_col() + 
    geom_text(aes(label = if_else(percent > .05, 
                                  scales::percent(percent, accuracy = .1), 
                                  ""), 
                  group = !!fill_col), 
              position = position_stack(vjust = .5)) +
    theme_classic() + 
    scale_y_continuous(labels = scales::percent) + 
    labs(y = "Percent", 
         caption = "Groups less than 5% suppressed for clarity") + 
    erase_y_axis + 
    erase_x_legend
    
    
}


```

Research Questions of Interest
- Are Opportunity Youth caring for children?
- What are the household income characteristics of Opportunity Youth?

## Partnered

```{r}

analysis_data$partnered %>% 
  ggplot(aes(x = oy_flag, y = percent, fill = PARTNER_label)) + 
  geom_col()
  



```

## Marital Status
```{r}

```


